version: '3.8'

services:
  jenkins:
    build:
      context: ./devops/docker
      dockerfile: jenkins.Dockerfile
    container_name: jenkins-container
    restart: unless-stopped
    privileged: true
    user: root
    network_mode: "host"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
    command: java -Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true -jar /usr/share/jenkins/jenkins.war --prefix=/jenkins

volumes:
  jenkins-home:

