version: "3.8"

services:
  nginx:
    build:
      context: ./devops/docker
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    env_file:
      - ../.env

networks:
  app-network:
    external: true
