version: "3.8"

services:
  nginx:
    build:
      context: ./devops
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
    networks:
      - app-network

networks:
  app-network:
    external: true
