version: '3.8'

services:
  jenkins:
    build:
      context: ./devops/docker
      dockerfile: jenkins.Dockerfile
    container_name: jenkins-container
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    command: >
      java
      -Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true
      -jar /usr/share/jenkins/jenkins.war
      --prefix=/jenkins
    dns:
      - 168.126.63.1   # KT DNS
      - 8.8.8.8        # Google DNS
      - 8.8.4.4        # Google DNS
    networks:
      - app-network

volumes:
  jenkins-home:

networks:
  app-network:
    external: true
