version: '3.8'

services:
  jenkins:
    build:
      context: ./devops/docker
      dockerfile: jenkins.Dockerfile
    container_name: jenkins-container
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
    networks:
      - app-network

volumes:
  jenkins-home:

networks:
  app-network:
    external: true
