version: '3.8'

services:
  mysql:
    build:
      context: ./devops/docker
      dockerfile: master-mysql.Dockerfile
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SERVICE_NAME}
      MYSQL_USER: ${DB_MYSQL_ID}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_BATCH_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_BATCH_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - app-network
    
volumes:
  mysql-data:
  redis-data:


networks:
  app-network:
    external: true
