server:
  servlet:
    context-path: /api

spring:
  application:
    name: ${SERVICE_NAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_ID}
    password: ${DB_MYSQL_PASSWORD}
    url: jdbc:mysql://${DB_MYSQL_URL}/${SERVICE_NAME}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect

  auth:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY}
